---
device_type: iosxr
commands:
  - "show ospf {{ process.id }}"
  - "show ospf {{ process.id }} neighbor area-sorted"
  - "show ospf {{ process.id }} database database-summary"
  - "show ospf {{ process.id }} statistics interface"
...
