---
# group_vars/ospf_routers.yml
all:
  ospf_routers:
    hosts:
      R1:
        vars:
          device_type: ios  # ios is only choice, iosxr coming soon
          my_areas: [0]
          my_nbr_count: 2
      R2:
        vars:
          device_type: ios
          my_areas: [0]
          my_nbr_count: 2
...
