---
# group_vars/ospf_routers.yml
all:
  hosts:
    localhost:
      log: true
  children:
    ospf_routers:
      children:
        ios:
          hosts:
            csr1:
              my_areas: [0]
              my_nbr_count: 2
            csr2:
              my_areas: [0, 51, 300]
              my_nbr_count: 2
              should_be_asbr: true
              should_be_stub_rtr: true
        iosxr:  # coming soon
        nxos:  # coming soon
        asa:  # coming soon
...
