---
# group_vars/ospf_routers.yml
all:
  children:
    ospf_routers:
      hosts:
        csr1.njrusmc.net:
          device_type: ios  # ios is only choice, iosxr coming soon
          my_areas: [0]
          my_nbr_count: 2
        csr2.njrusmc.net:
          device_type: ios
          my_areas: [0, 51]
          my_nbr_count: 2
...
