---
- hosts: localhost
  tasks:
    - set_fact:
        text: |-
          Routing Process "ospf 1" with ID 192.168.0.12
          Role: Primary Active
          NSR (Non-stop routing) is Disabled
          Supports only single TOS(TOS0) routes
          Supports opaque LSA
          It is an area border and autonomous system boundary router
          Router is not originating router-LSAs with maximum metric
          Initial SPF schedule delay 50 msecs
          Minimum hold time between two consecutive SPFs 200 msecs
          Maximum wait time between two consecutive SPFs 5000 msecs
          Initial LSA throttle delay 50 msecs
          Minimum hold time for LSA throttle 200 msecs
          Maximum wait time for LSA throttle 5000 msecs
          Minimum LSA interval 200 msecs. Minimum LSA arrival 100 msecs
          LSA refresh interval 1800 seconds
          Flood pacing interval 33 msecs. Retransmission pacing interval 66 msecs
          Adjacency stagger enabled; initial (per area): 2, maximum: 64
             Number of neighbors forming: 0, 1 full
          Maximum number of configured interfaces 1024
          Number of external LSA 0. Checksum Sum 00000000
          Number of opaque AS LSA 0. Checksum Sum 00000000
          Number of DCbitless external and opaque AS LSA 0
          Number of DoNotAge external and opaque AS LSA 0
          Number of areas in this router is 2. 1 normal 0 stub 1 nssa
          External flood list length 0
          SNMP trap is enabled
          LSD connected, registered, bound, revision 1
          Segment Routing Global Block default (16000-23999), not allocated
             Area BACKBONE(0)
                 Number of interfaces in this area is 1
                 SPF algorithm executed 7 times
                 Number of LSA 4.  Checksum Sum 0x018095
                 Number of opaque link LSA 0.  Checksum Sum 00000000
                 Number of DCbitless LSA 0
                 Number of indication LSA 0
                 Number of DoNotAge LSA 0
                 Flood list length 0
                 Number of LFA enabled interfaces 0, LFA revision 0
                 Number of Per Prefix LFA enabled interfaces 0
                 Number of neighbors forming in staggered mode 0, 1 full
             Area 51
                 Number of interfaces in this area is 1
                 It is a NSSA area
                 Perform type-7/type-5 LSA translation
                 SPF algorithm executed 1 times
                 Number of LSA 2.  Checksum Sum 0x009e2a
                 Number of opaque link LSA 0.  Checksum Sum 00000000
                 Number of DCbitless LSA 0
                 Number of indication LSA 0
                 Number of DoNotAge LSA 0
                 Flood list length 0
                 Number of LFA enabled interfaces 51, LFA revision 0
                 Number of Per Prefix LFA enabled interfaces 0
                 Number of neighbors forming in staggered mode 0, 0 full
        
    - set_fact:
        data: "{{ text | iosxr_ospf_basic }}"

    - debug:
        var: data

    - set_fact:
        text: |-
          OSPF Router with ID (192.168.0.12) (Process ID 1)
          
          Area 0 database summary
            LSA Type      Count    Delete   Maxage
            Router        2        0        0       
            Network       1        0        0       
            Summary Net   1        0        0       
            Summary ASBR  0        0        0       
            Type-7 Ext    0        0        0       
            Opaque Link   0        0        0       
            Opaque Area   0        0        0       
            Subtotal      4        0        0       
          
          Area 51 database summary
            LSA Type      Count    Delete   Maxage
            Router        1        0        0       
            Network       0        0        0       
            Summary Net   1        0        0       
            Summary ASBR  0        0        0       
            Type-7 Ext    0        0        0       
            Opaque Link   0        0        0       
            Opaque Area   0        0        0       
            Subtotal      2        0        0       
          
          Process 1 database summary
            Router        3        0        0       
            Network       1        0        0       
            Summary Net   2        0        0       
            Summary ASBR  0        0        0       
            Type-7 Ext    0        0        0       
            Opaque Link   0        0        0       
            Opaque Area   0        0        0       
            Type-5 Ext    0        0        0       
            Opaque AS     0        0        0       
            Total         6        0        0      

    - set_fact:
        data: "{{ text | ios_ospf_dbsum }}"  # same as IOS?

    - debug:
        var: data


    - set_fact:
        text: |-
          Interface GigabitEthernet0/0/0/0.511 Process ID 1 Area 0
          
          OSPF packet and LSA statistics
                    RX(hello) RX(router)        TX     LSA RX     LSA TX
          Hello           36          -         37          -          -
          DB Des           7          7          2          1          1
          LS Req           1          1          1          1          0
          LS Upd           3          3          6          3          6
          LS Ack           3          3          2          5          2
          TOTAL           50         14         48         10          9
          
            OSPF Header Errors
          Version                    0      LLS                        0
          Type                       0      Auth RX                    0
          Length                     0      Auth TX                    0
          Checksum                   0
          
            OSPF LSA Errors
          Type                       0      Checksum                   0
          Length                     0      Data                       0
          
            OSPF Errors
          Bad Source                 0      Area Mismatch              0
          No Virtual Link            0      Self Originated            0
          No Sham Link               0      Duplicate ID               0
          Nbr ignored                0      Graceful Shutdown          0
          Unknown nbr                0      Passive intf               0
          No DR/BDR                  0      Disabled intf              0
          Enqueue hello              0      Enqueue router             0
          Unspecified RX             0      Unspecified TX             0
          Socket                     0
          
                  Interface Loopback51 Process ID 1 Area 51
          
          OSPF packet and LSA statistics
                    RX(hello) RX(router)        TX     LSA RX     LSA TX
          Hello            0          -          0          -          -
          DB Des           0          0          0          0          0
          LS Req           0          0          0          0          0
          LS Upd           0          0          0          0          0
          LS Ack           0          0          0          0          0
          TOTAL            0          0          0          0          0
          
            OSPF Header Errors
          Version                    0      LLS                        0
          Type                       0      Auth RX                    0
          Length                     0      Auth TX                    0
          Checksum                   0
          
            OSPF LSA Errors
          Type                       0      Checksum                   0
          Length                     0      Data                       0
          
            OSPF Errors
          Bad Source                 0      Area Mismatch              0
          No Virtual Link            0      Self Originated            0
          No Sham Link               0      Duplicate ID               0
          Nbr ignored                0      Graceful Shutdown          0
          Unknown nbr                0      Passive intf               0
          No DR/BDR                  0      Disabled intf              0
          Enqueue hello              0      Enqueue router             0
          Unspecified RX             0      Unspecified TX             0
          Socket                     0

    - set_fact:
        data: "{{ text | iosxr_ospf_traffic }}"

    - debug:
        var: data


    - set_fact:
        text: |-
          * Indicates MADJ interface
          
          Neighbors for OSPF 1
          
          Area 0
          Neighbor ID     Pri State    Dead Time Address         Up Time  Interface
          192.168.0.12    1   FULL/DR  00:00:32  192.168.0.12    00:18:57 Gi0/0/0/0.511

    - set_fact:
        data: "{{ text | iosxr_ospf_neighbor }}"

    - debug:
        var: data
